language: python
python:
  - "3.7"
  - "3.9"

install:
  - pip install .
  - pip install -r tests/requirements.txt

env:
  - PYTHONPATH=.

# command to run tests
script:
  - python -m unittest discover tests
